### ISSUE TITLE
Требуется усилить уникальность HashAddress

### ISSUE THREAD

**Issue by Stepami** [Stepami/hydrascript#29]
Сейчас уникальность генерируемого адреса базируется лишь на `seed`, передаваемом в конструктор:

```cs
public class HashAddress : IAddress
{
    private readonly int _seed;

    public HashAddress(int seed) =>
        _seed = seed;

    public bool Equals(IAddress other)
    {
        if (other is HashAddress hashed)
            return _seed == hashed._seed;

        return false;
    }
}
```

В качестве `seed` используется хэш-код инструкции, которой присваивается адрес: `instruction.GetHashCode()`.
Поскольку `GetHashCode` не переопределён в иерархии инструкций, то по сути это отражение выделения памяти.
В любом, случае чем больше будет инструкций, тем больше вероятность того, что произойдёт коллизия, и для два экземпляра `HashAddress` с одинаковым `seed` будут означать один и тот же адрес.

Это поведение нужно исправить.

Предлагается добавить приватное поле `Guid _id = Guid.NewGuid()`

**Comment by nazarovsa** [comment]
Предлагается добавить `_id` вместо `seed`?  
Должен ли конструктор поддерживать аргумент `Guid id`, или `_id` всегда будет `Guid.NewGuid()`?

**Comment by Stepami** [comment]
@nazarovsa "семечко" остаётся для инициализации и вычисления хешкода, а гуидник создаётся внутри для того, чтобы два экземпляра,  созданных с одним сидом были не равны:
`new HashAdress(seed: 1) != new HashAdress(seed: 1)`

**Comment by nazarovsa** [comment]
@Stepami Для чего делать Guid, почему просто не проверить ссылки?

**Comment by Stepami** [comment]
@nazarovsa Как будто история с `Guid` это более читаемый и понятный программисту способ запрета воспроизведения равного объекта by design

**Comment by nazarovsa** [comment]
Возможно, но это дополнительный оверхед на память. А этих экземпляров будем много, насколько я понимаю.  
Райдер предлагает такой автогенерированный код:
```csharp
    protected bool Equals(HashAddress other)
    {
        return _seed == other._seed;
    }

    public override bool Equals(object obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != this.GetType()) return false;
        return Equals((HashAddress)obj);
    }
```
Кажется, что этого достаточно.

**Comment by Stepami** [comment]
@nazarovsa

думаю, что беспокоиться о памяти излишне - скрипты до 100 строк => экземпляры адресов исчисляются порядком 10-100

основное требование:
```cs
new HashAdress(seed: 1).Equals(new HashAdress(seed: 1)).Should().BeFalse()
```

**Comment by nazarovsa** [comment]
Я подготовил два МРа для сравнения. Выбери, что бы ты хотел видеть.  
https://github.com/nazarovsa/hydrascript/pull/1
https://github.com/nazarovsa/hydrascript/pull/2

**Comment by Stepami** [comment]
@nazarovsa Однозначно https://github.com/nazarovsa/hydrascript/pull/1 )
 
Это ещё понадобится для https://github.com/Stepami/hydrascript/issues/30, чтобы использовать гуидник в наименовании адреса (+ уникальность)
 
 переоткрой пожалуйста PR'ы так, чтобы они метили в мою репу, а не в форк
